#!/bin/bash
#linode GPU cluster script NVIDIA (Fedora 34)
echo "fedora 34 linode GPU cluster script"
echo "script part 1, script has to reboot after install cuda and nvidia deps"
echo "networking might require https://raw.githubusercontent.com/c4pt000/kernel-5.11.6-expSEHDsec-HAXM-cgroup-virtio-nvidia-amd/master/patch-libvirt-IPTABLES-NFTABLES-UFW.sh"

sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io -y
systemctl start docker
systemctl enable docker

wget -O /etc/yum.repos.d/inttf.repo https://rpms.if-not-true-then-false.com/inttf.repo
dnf install nvidia-docker2 -y

echo " 
disable-require = false
#swarm-resource = DOCKER_RESOURCE_GPU
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
#accept-nvidia-visible-devices-as-volume-mounts = false
[nvidia-container-cli]
#root = /run/nvidia/driver
#path = /usr/bin/nvidia-container-cli
environment = []
#debug = /var/log/nvidia-container-toolkit.log
#ldcache = /etc/ld.so.cache
load-kmods = true
no-cgroups = true
#user = root:video
ldconfig = @/sbin/ldconfig
[nvidia-container-runtime]
debug = /var/log/nvidia-container-runtime.log 
" >  /etc/nvidia-container-runtime/config.toml 

systemctl restart docker



wget https://developer.download.nvidia.com/compute/cuda/repos/fedora33/x86_64/cuda-fedora33.repo
mv cuda-fedora33.repo /etc/yum.repos.d/
yum install cuda nvidia-driver -y

echo "
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
export PATH=$PATH:$CUDA_HOME/bin
" >> /root/.bashrc

source /root/.bashrc


wget https://us.download.nvidia.com/XFree86/Linux-x86_64/465.19.01/NVIDIA-Linux-x86_64-465.19.01.run
chmod +x NVIDIA-Linux-x86_64-465.19.01.run

rm -rf /root/.bashrc
wget https://raw.githubusercontent.com/c4pt000/kernel-5.11.6-expSEHDsec-HAXM-cgroup-virtio-nvidia-amd/master/linode-bashrc && cp -rf linode-bashrc /root/.bashrc && source /root/.bashrc
wget https://raw.githubusercontent.com/c4pt000/kernel-5.11.6-expSEHDsec-HAXM-cgroup-virtio-nvidia-amd/master/grub-linode-fedora34 && cp -rf grub-linode-fedora34 /etc/default/grub









wget https://github.com/c4pt000/kernel-5.11.6-expSEHDsec-HAXM-cgroup-virtio-nvidia-amd/releases/download/haxm-experimental/kernel-5.11.6_HAXM_expSEHDsec_c4pt000_amdNV-1.x86_64.rpm 
wget https://github.com/c4pt000/kernel-5.11.6-expSEHDsec-HAXM-cgroup-virtio-nvidia-amd/releases/download/haxm-experimental/kernel-headers-5.11.6_HAXM_expSEHDsec_c4pt000_amdNV-1.x86_64.rpm 
wget https://github.com/c4pt000/kernel-5.11.6-expSEHDsec-HAXM-cgroup-virtio-nvidia-amd/releases/download/haxm-experimental/kernel-devel-5.11.6_HAXM_expSEHDsec_c4pt000_amdNV-1.x86_64.rpm 
yum install kernel*.rpm -y
yum install mesa* vulkan* libglv* -y
rm -rf /boot/initramfs-5.11.*300*
rm -rf /boot/vmlinu*300*

grub2-mkconfig -o /boot/grub2/grub.cfg && grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg 
echo "script needs to reboot for changes to kernel and kernel-devel script will pause for 10 seconds"
sleep 10s
wget https://raw.githubusercontent.com/c4pt000/radioCOIN/main/LINODE-GPU-CLUSTER-script-FEDORA-34.pt2
chmod +x LINODE-GPU-CLUSTER-script-FEDORA-34.pt2
echo "script part 2 after reboot"
echo "./LINODE-GPU-CLUSTER-script-FEDORA-34.pt2"
echo "rebooting now"
echo "newer kernel takes 90 seconds to boot to load kobjects and events"
systemctl enable docker
systemctl start docker
nvidia-smi
reboot
